// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputUser struct {
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type VerifyEmail struct {
	Email string `json:"email"`
	Token string `json:"token"`
}

type NewPost struct {
	Content []*NewPostContent `json:"content"`
	Caption string            `json:"caption"`
	UserID  string            `json:"user_id"`
}

type NewPostContent struct {
	Path string `json:"path"`
	Type string `json:"type"`
}

type NewRelation struct {
	FollowID   string `json:"follow_id"`
	FollowedID string `json:"followed_id"`
}

type UpdatePassword struct {
	Token    string `json:"token"`
	Password string `json:"password"`
}
